# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Zack Daniels
title: Senior Network System Administrator
email: nullfacesecurity@protonmail.com
website: cavemanguy.github.io

# About Section
# about_title: About Me
about_profile_image: profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Zack and I'm a self taught network system administrator. As well as administrating systems I also have experience scripting and making simple web apps. I love honesty and transparency in interested employeers. If I don't know the answer I won't pretend to but I will work hard to find a solution.
  I am most skilled in: <mark>Administration</mark> and <mark>Security</mark> 
  
  I am pretty handy in the following for development purposes.
  * Javascript
  * HTML,HTML5
  * CSS
  * AWS
  * Active Directory
  * Apache
  * A little of everything

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
